# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10biPk3KoPeSvk8zcloHsnKkUbNIYFQ6A
"""

print('my git hub project')
print('upload to git')
print(2+3)

